package BasicHTMLGeneratorParser.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ColorVersion extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ColorVersion() {
    super(0xc5b04c8306054412L, 0x977887c884988a45L, 0x2c77447521800c96L, "ColorVersion", "r:b0473809-af0c-4a38-9b87-8a1cd23e0d1d(BasicHTMLGeneratorParser.structure)/3204104929761299606");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_white_0 = new EnumerationDescriptor.MemberDescriptor("white", "WHITE", 0x2c77447521800c97L, "r:b0473809-af0c-4a38-9b87-8a1cd23e0d1d(BasicHTMLGeneratorParser.structure)/3204104929761299607");
  private final EnumerationDescriptor.MemberDescriptor myMember_black_0 = new EnumerationDescriptor.MemberDescriptor("black", "BLACK", 0x2c77447521800c98L, "r:b0473809-af0c-4a38-9b87-8a1cd23e0d1d(BasicHTMLGeneratorParser.structure)/3204104929761299608");
  private final EnumerationDescriptor.MemberDescriptor myMember_green_0 = new EnumerationDescriptor.MemberDescriptor("green", "GREEN", 0x2c77447521800c9bL, "r:b0473809-af0c-4a38-9b87-8a1cd23e0d1d(BasicHTMLGeneratorParser.structure)/3204104929761299611");
  private final EnumerationDescriptor.MemberDescriptor myMember_pink_0 = new EnumerationDescriptor.MemberDescriptor("pink", "PINK", 0x2c77447521800c9fL, "r:b0473809-af0c-4a38-9b87-8a1cd23e0d1d(BasicHTMLGeneratorParser.structure)/3204104929761299615");
  private final EnumerationDescriptor.MemberDescriptor myMember_yellow_0 = new EnumerationDescriptor.MemberDescriptor("yellow", "YELLOW", 0x2c77447521800caeL, "r:b0473809-af0c-4a38-9b87-8a1cd23e0d1d(BasicHTMLGeneratorParser.structure)/3204104929761299630");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc5b04c8306054412L, 0x977887c884988a45L, 0x2c77447521800c96L, 0x2c77447521800c97L, 0x2c77447521800c98L, 0x2c77447521800c9bL, 0x2c77447521800c9fL, 0x2c77447521800caeL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_white_0, myMember_black_0, myMember_green_0, myMember_pink_0, myMember_yellow_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "white":
        return myMember_white_0;
      case "black":
        return myMember_black_0;
      case "green":
        return myMember_green_0;
      case "pink":
        return myMember_pink_0;
      case "yellow":
        return myMember_yellow_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
