package BasicHTMLGeneratorParser.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BotonTag = 0;
  public static final int BotonsTag = 1;
  public static final int Color = 2;
  public static final int Columna = 3;
  public static final int Componentes = 4;
  public static final int ContenidoOpcion = 5;
  public static final int Document = 6;
  public static final int Element = 7;
  public static final int ElementBoton = 8;
  public static final int Elements = 9;
  public static final int Etiqueta = 10;
  public static final int EtiquetaTag = 11;
  public static final int EtiquetasTag = 12;
  public static final int Formulario = 13;
  public static final int Opcion = 14;
  public static final int OpcionSelector = 15;
  public static final int OpcionsSelector = 16;
  public static final int SelectorsTag = 17;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc5b04c8306054412L, 0x977887c884988a45L);
    builder.put(0x2c774475217a8f09L, BotonTag);
    builder.put(0x2c774475217a8f07L, BotonsTag);
    builder.put(0x2c774475217a8f0aL, Color);
    builder.put(0x2c774475217a8efcL, Columna);
    builder.put(0x2c774475217a8efeL, Componentes);
    builder.put(0x2c774475217a8f06L, ContenidoOpcion);
    builder.put(0x4e1fcda545f5ef3bL, Document);
    builder.put(0x2c774475217a8efdL, Element);
    builder.put(0x2c774475217a8f08L, ElementBoton);
    builder.put(0x4e1fcda545f5ef3cL, Elements);
    builder.put(0x2c774475217a8f00L, Etiqueta);
    builder.put(0x2c774475217a8f01L, EtiquetaTag);
    builder.put(0x2c774475217a8effL, EtiquetasTag);
    builder.put(0x2c774475217a8f1eL, Formulario);
    builder.put(0x2c774475217a8f04L, Opcion);
    builder.put(0x2c774475217a8f05L, OpcionSelector);
    builder.put(0x2c774475217a8f03L, OpcionsSelector);
    builder.put(0x2c774475217a8f02L, SelectorsTag);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
